Payload loader
Pyxsys/ttg-healthcheck pull request #132
Opened 2021-10-29 18:29 UTC by Pyxsys

* Added unique machine identifier to daemon payload
* Added implementation to dameon_endpoint to add cpu logs to DB
  * Added helper function to cpu model to clarify responsibilities
* Added tests for new daemon feature
* Added tests for new api feature

closes #131 
closes #110
closes #7

2021-10-29 18:43 UTC, DerekRuiz commented on server/models/process.js
> +const Processes = mongoose.model('processes', ProcessSchema)
Does not require model if there is no collection for the Schema

2021-10-29 18:51 UTC, DerekRuiz commented on server/models/cpu.js
> +
Functions do not belong in the models folder, relocate to API folder or a new file for extracting  information from the PI device
Model folder is only for defining schemas and models (collections)

2021-10-29 18:56 UTC, DerekRuiz requested changes
- [ ] Move the function to instantiate a new CpuLog object outside of the Model folder
- [x] If the Process schema does not require its own collection, remove the creating of `const Processes = mongoose.model('processes', ProcessSchema)`

The tests look proper

2021-10-29 20:56 UTC, Pyxsys commented on server/models/process.js
> +const Processes = mongoose.model('processes', ProcessSchema)
Process model was created as child for parent CpuLog.
A CpuLog contains many processes.

@DerekRuiz Please clarify.

2021-10-29 22:01 UTC, Pyxsys commented on server/models/process.js
> +const Processes = mongoose.model('processes', ProcessSchema)
mongoose.model creates a doc in the DB. Will remove

2021-10-29 22:05 UTC, Pyxsys commented on server/models/cpu.js
> +
After discussion,  extracted method will be moved to `api/daemon_endpoint`.

2021-10-30 15:08 UTC, Pyxsys commented on server/models/process.js
> +const Processes = mongoose.model('processes', ProcessSchema)
[Commit added](https://github.com/Pyxsys/ttg-healthcheck/pull/132/commits/ade3c48f53fa413188338190b2d3b04ca080e696)

2021-10-30 15:09 UTC, Pyxsys commented on server/models/cpu.js
> +
[commit added](https://github.com/Pyxsys/ttg-healthcheck/pull/132/commits/ade3c48f53fa413188338190b2d3b04ca080e696)

2021-10-30 15:13 UTC, DerekRuiz approved these changes
Changes approved

2021-10-30 18:22 UTC, shash3 approved these changes
Everything looks good. I have 1 suggestion about the name of daemon_endpoint.js. I don't think we need to add "_endpoint" at the end as it is already in the api folder

2021-10-31 20:01 UTC, merged